// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ContainerPlanPredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("Scenario"), LoadColumn(0)]
        public string Scenario { get; set; }


        [ColumnName("Row"), LoadColumn(1)]
        public float Row { get; set; }


        [ColumnName("Bay"), LoadColumn(2)]
        public float Bay { get; set; }


        [ColumnName("RouteNumber"), LoadColumn(3)]
        public float RouteNumber { get; set; }


        [ColumnName("ContainerType"), LoadColumn(4)]
        public string ContainerType { get; set; }


        [ColumnName("ContainerSize"), LoadColumn(5)]
        public string ContainerSize { get; set; }


        [ColumnName("ContainerContentType"), LoadColumn(6)]
        public string ContainerContentType { get; set; }


    }
}
