// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using ContainerPlanPredictionML.Model;

namespace ContainerPlanPredictionML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\lukes\AppData\Local\Temp\8e851cdd-559d-4c46-b6ad-84f83823a7a8.tsv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Row with predicted Row from sample data...\n\n");
            Console.WriteLine($"Scenario: {sampleData.Scenario}");
            Console.WriteLine($"Bay: {sampleData.Bay}");
            Console.WriteLine($"RouteNumber: {sampleData.RouteNumber}");
            Console.WriteLine($"ContainerType: {sampleData.ContainerType}");
            Console.WriteLine($"ContainerSize: {sampleData.ContainerSize}");
            Console.WriteLine($"ContainerContentType: {sampleData.ContainerContentType}");
            Console.WriteLine($"\n\nActual Row: {sampleData.Row} \nPredicted Row value {predictionResult.Prediction} \nPredicted Row scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
